### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by chrisnharvey** [probonopd/SystemImageKit#2]
SystemImageKit is amazing! I'm really looking forward to using it for my distro. I do have a few questions though:

1. How are users saved? If I do ```useradd chris```, this user is gone when I reboot.

2. Could I run all of this from one partition? (/boot, /apps, /home)

3. How can config files be stored in a persistent way? So if I reorder my gnome dock, how can this change remain after reboot?

4. If I'm using AppImages and need to add these to the gnome menu, would I have to run something every time to extract the icons and .desktop files and place them in /usr/share/applications? Because won't these files be deleted on reboot?

**Comment by probonopd** [comment]
Very valid questions you raise.

1. Currently I do all of this using ExtensionImages (basically lilke AppImages but their contents are symlinked over /)

2. Yes

3. I have not implemented this. I do my configurations in scripts that run at each boot. But for general users a persistent $HOME would be more appropriate.

4. Correct, you'd need something like appimaged

**Comment by chrisnharvey** [comment]
Perhaps overlayfs might be a viable solution? https://www.kernel.org/doc/Documentation/filesystems/overlayfs.txt

**Comment by chrisnharvey** [comment]
So I'm thinking that I could have a directory alongside /boot called /data which would be mounted over the ISO filesystem.

```
mount -t overlayfs -o lowerdir=/,upperdir=/isodevice/data overlayfs /
```

But I need to do this before the live filesystem is mounted at /.

Can you think of a way in which I could achieve this?

If I can get this working then thats pretty much all I need to get this working for my use case.

**Comment by probonopd** [comment]
If you want to do things before / is mounted in a Fedora live system, then you probably have to modify/add a dracut hook. You would do this by adding a directory in SystemImageKit/boot/iso/additional-initramfs/ and put your dracut hook(s) there, similar to what I did in SystemImageKit/boot/iso/additional-initramfs/dracut-deltadir-support/usr/lib/dracut/hooks/pre-pivot/30-deltadir.sh

According to https://events.linuxfoundation.org/images/stories/pdf/lcjp2012_cong_wang.pdf the best place to put your hook might be "pre-mount: right before mounting rootfs".

**Comment by chrisnharvey** [comment]
Hi @probonopd 

Many thanks for your advice.

I'm making some progress with this.

Essentially what I need to do is the following in the initramfs

```
mount --move / /os
mount <isodevice> /system
mount -t overlayfs -o lowerdir=/os,upperdir=/system/data overlayfs /
```

I'm just having trouble moving the root filesystem to another mount point. Then I can mount the HDD (SystemImageKit files) as read/write under /system then mount the root filesystem as an overlayfs of /os (original ISO root filesystem) and /system/data (a *real* directory on the HDD which sits alongside /boot).

In theory this should work if I can move the root filesystem.

I've tried this from the terminal my mounting the HDD under /mnt then running:
```
mount -t overlayfs -o lowerdir=/,upperdir=/mnt/data overlayfs /test
```

Then all my files are then stored in /mnt/data, and are merged with the root filesystem under the /test mount point.

I just need a way to get this same functionality working but under the root mount point instead of /test.

**Comment by probonopd** [comment]
I think these questions can best be answered at https://github.com/haraldh/dracut - unfortunately I don't know the inner workings of the dracut live mounting system very well. Most likely you can find out how it works by studying the source code in dracut/modules.d/90dmsquash-live there.

**Comment by probonopd** [comment]
@chrisnharvey Did you ever find out how to use overlayfs with Fedora? Please see https://github.com/haraldh/dracut/issues/104 and if you have an idea, please join that discussion. I would really like to use overlayfs instead of dmsquash so that Fedora live systems become usable and don't crash after doing some filesystem operations. Thanks!
