### ISSUE TITLE
Why vFAT?

### ISSUE THREAD

**Issue by chrisnharvey** [probonopd/SystemImageKit#3]
Is there a technical reason why the HDD needs to be formatted as vFAT, or would ext4 work fine too?

**Comment by probonopd** [comment]
Not entirely sure; as I am just using USB sticks which I want to be able to mount everywhere I didn't try...

**Comment by chrisnharvey** [comment]
Cool, I'll give this a try tonight. I can't really see the why it wouldn't work.

I'll let you know how I get on.

**Comment by probonopd** [comment]
Please test again, I have removed some fat-specific code

**Comment by chrisnharvey** [comment]
All working perfectly! Many thanks for this!
