### ISSUE TITLE
Casper support strange live_args

### ISSUE THREAD

**Issue by adrian15** [probonopd/SystemImageKit#47]
https://github.com/probonopd/SystemImageKit/blob/d0fb7c5972d5488a7c4cea10829dfa985030f948/boot/bin/detect_casper.sh#L52

```
live_args="for-casper --> iso-scan/filename=\${iso_path} console-setup/layoutcode=$KEYBOARD locale=$LANGUAGE timezone=$TIMEZONE username=$USERNAME hostname=$HOSTNAME noprompt init=/isodevice/boot/customize/init max_loop=256"
```

The:
```
for-casper -->
```
string seems to be a wrong leftover of a manual copy and paste.

**Comment by probonopd** [comment]
No, it is intentional and is for information. It should not hurt. Please comment if you think it does hurt.

**Comment by adrian15** [comment]
It does not hurt. Kernel, initrd and other scripts will read it and ignore it.
It seems more of a thing that should go into a comment and not inside of an actual used variable.
