### ISSUE TITLE
dude I have few questions for you.

### ISSUE THREAD

**Issue by ghost** [probonopd/SystemImageKit#50]
can you send me an email?
lucasmzainote@gmail.com
I don't know how to use this development platform.

**Comment by ghost** [comment]
stalking here

**Comment by probonopd** [comment]
Please ask your questions here so that everyone can learn from the answers. Thanks!

**Comment by ghost** [comment]
can we trade a few stickers ? email me ? I have pretty good ones sir.

Em qui., 23 de jul. de 2020 às 16:41, probonopd <notifications@github.com>
escreveu:
