### ISSUE TITLE
Get file manager and terminal to show hard disk contents instead of ISO contents

### ISSUE THREAD

**Issue by chrisnharvey** [probonopd/SystemImageKit#6]
In your YouTube video, I noticed that when you entered your file browser and selected your root directory, the contents of the hard disk were shown and not the contents of the ISO.

How did you do this?

I need to show the contents of the hard disk under "Computer" in Nautilus so I can access the apps and hide the read-only ISO instead of navigating to the isodevice mount point.

Is this also possible when navigating to the root directory in the terminal? So I do:
```bash
cd /
```
and be given the hard disk contents which currently has an ```Apps``` and a ```boot``` directory.

**Comment by probonopd** [comment]
In `customize/init` or a start script, you could symlink or (bind-)mount stuff to / and/or hide stuff from / using a `.hidden` file. That is what I did back then, anyway. In case this is a generally wanted feature we could add it to `customize/init` for everyone. Should however be made in a way that works on any live ISO...

**Comment by probonopd** [comment]
Implemented
