### ISSUE TITLE
License

### ISSUE THREAD

**Issue by chrisnharvey** [probonopd/SystemImageKit#7]
As you know, I'm planning on using SystemImageKit for a Linux distro I'm developing.

I will be modifying SystemImageKit quite a bit with specific code for my distro.

I'm just wondering what the license is for SystemImageKit and AppImageKit? A lot of the changes/improvements I make will be contributed back to this repository, but others will be code which would not really fit within the main SystemImageKit repository.

**Comment by probonopd** [comment]
I have not decided yet and am currently considering GPL, BSD, Apache, or MIT. What is your view on that?

**Comment by RazZziel** [comment]
If I may, personally I like the [WTFPL](http://www.wtfpl.net/) ;)

**Comment by chrisnharvey** [comment]
@RazZziel I had a feeling that would be your favourite.

I usually release my stuff under MIT, but GPL might work well for these projects as they'd fit in with what the Linux community is used to.
